# Generated by Django 3.2.5 on 2022-03-20 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accel_x', models.FloatField(default=0, max_length=50)),
                ('accel_y', models.FloatField(default=0, max_length=50)),
                ('accel_z', models.FloatField(default=0, max_length=50)),
                ('distance', models.FloatField(default=0, max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=200)),
                ('trip_id', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('publisher', models.CharField(max_length=200)),
                ('trip_status', models.CharField(default='Progressing', max_length=50)),
                ('scooter_id', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(help_text='First name', max_length=50)),
                ('last_name', models.CharField(help_text='Last name', max_length=50)),
                ('email', models.EmailField(help_text='username@email.com', max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
